#!/usr/bin/env python3
"""devbrain — shared rules, defined ONCE instead of copied across capture.sh,
capture-response.sh, capture-memory.sh and import.py: redact() (secrets),
is_synthetic() (injected prompts), recap()/sample() (the one merged-#15 response
summarizer — closing sentence + head/middle body), remote_to_key() (routing).

Used directly by import.py and the capture-response heredoc, and as a CLI by the
bash hooks:
  printf %s "$text"    | devbrain_lib.py redact            -> redacted text
  printf %s "$prompt"  | devbrain_lib.py prompt-filter     -> redacted prompt, or EMPTY if
                                                             synthetic (caller skips)
  printf %s "$payload" | devbrain_lib.py read-event FIELD  -> one normalized field from a
                                                             host-harness hook payload (JSON)
  printf %s "$msg" | devbrain_lib.py session-start-context -> SessionStart additionalContext JSON
  devbrain_lib.py register-hook FILE EVENT MATCHER COMMAND -> idempotently add a hook to settings.json
  devbrain_lib.py unregister-hook FILE COMMAND...          -> strip those hook commands from settings.json
Pure stdlib, no import side effects, cheap to call per event. This is also the ONE
place that touches settings.json, so the install/uninstall path needs no `jq` — python3
(already required for capture) is the sole parse dependency.
"""
import datetime, json, os, re, shlex, sys, tempfile
from collections import OrderedDict, deque

# High-confidence, prefix-anchored secret shapes. Equivalent to the sed program the
# bash hooks used to each carry — same patterns, one definition.
_REDACT = [
    (re.compile(r"sk-[A-Za-z0-9_-]{20,}"), "[REDACTED]"),
    (re.compile(r"(gh[pousr]_)[A-Za-z0-9]{20,}"), r"\1[REDACTED]"),
    (re.compile(r"github_pat_[A-Za-z0-9_]{20,}"), "[REDACTED]"),
    (re.compile(r"(AKIA|ASIA)[0-9A-Z]{16}"), "[REDACTED]"),
    (re.compile(r"xox[baprs]-[A-Za-z0-9-]{10,}"), "[REDACTED]"),
    (re.compile(r"(Bearer )[A-Za-z0-9._-]{16,}"), r"\1[REDACTED]"),
]

def redact(text):
    if not text:
        return text
    for rx, repl in _REDACT:
        text = rx.sub(repl, text)
    return text

# Injected "prompts" that carry no user authorship at all — pure host-harness noise.
# Keep this list MINIMAL and bias toward keeping: a turn that merely embeds the user's
# text inside a harness wrapper (e.g. a <system_instruction> preamble) is still a real
# prompt and must be captured whole, wrapper and all. Only list markers whose entire
# body is machine-generated with zero user content.
SYNTHETIC_PREFIXES = (
    "<system-reminder>",
    "<command-name>",
    "You are generating a short conversation title",
    "Caveat: The messages below were generated by the user",
    "Base directory for this skill:",
    # Codex injects the invoked skill's SKILL.md as a role=user response_item that
    # opens with `<skill><name>…`. It's machine-generated (the real prompt is the
    # typed `$skill`), and _codex_details credits it as Skill:<name> instead — so
    # in the rare session with no typed prompt it must never become a logged prompt.
    "<skill>",
)

def is_synthetic(text):
    return bool(text) and text.lstrip().startswith(SYNTHETIC_PREFIXES)

def recap(texts):
    """The turn's CLOSING sentence — the recap lives at the end of the final assistant
    message (per the CLAUDE.md convention). `texts` = the turn's assistant text blocks.
    This is the merged-#15 algorithm; the one recap definition for capture + import."""
    last_text = ""
    for t in texts:
        if t and t.strip():
            last_text = t
    chosen = ""
    for line in last_text.splitlines():
        s = re.sub(r"^[>\-\*\s]+", "", line.strip())
        if not s or s.startswith("#"):
            continue
        chosen = s   # keep going -> ends on the LAST substantive line
    if not chosen:
        chosen = re.sub(r"^[#>\-\*\s]+", "", last_text.strip())
    chosen = re.sub(r"\s+", " ", chosen).strip()
    parts = re.findall(r".+?[.!?](?:\s|$)", chosen)
    if parts:
        summary = parts[-1].strip()
        if len(summary) < 60 and len(parts) > 1:   # extend a too-short tail backwards
            summary = (parts[-2].strip() + " " + summary).strip()
    else:
        summary = chosen
    return summary[:500].strip()

def sample(texts):
    """A bounded head+middle SAMPLE of the whole turn's prose (the recap is the tail), so
    the log holds the reasoning, not just a headline. Short responses are kept whole; long
    ones are sampled to a fixed size with […] gap markers. Merged-#15 algorithm."""
    full = re.sub(r"\n{3,}", "\n\n", "\n\n".join(t.strip() for t in texts if t.strip()).strip())
    MAXCHARS, HEAD, MID = 4000, 2200, 1400   # MAXCHARS ~700 words; whole if under it
    if len(full) <= MAXCHARS:
        return full
    head = full[:HEAD].rsplit(" ", 1)[0].strip()            # snap off a partial word
    c = len(full) // 2
    mid = full[c - MID // 2 : c + MID // 2]
    mid = mid.split(" ", 1)[-1].rsplit(" ", 1)[0].strip()   # trim partial words both ends
    return head + "\n\n[…]\n\n" + mid + "\n\n[…]"

def _content_text(content):
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "".join(b.get("text", "") for b in content
                       if isinstance(b, dict) and b.get("type") == "text")
    return ""

def _assistant_details(events):
    texts, tools, files = [], OrderedDict(), OrderedDict()
    tin = tout = tcc = tcr = 0
    model = ""
    turn_ts = ""
    seen_ids = set()
    for e in events:
        if e.get("type") != "assistant":
            continue
        msg = e.get("message", {}) or {}
        mid = msg.get("id")
        if mid not in seen_ids:
            seen_ids.add(mid)
            usage = msg.get("usage") or {}
            tin += usage.get("input_tokens") or 0
            tout += usage.get("output_tokens") or 0
            tcc += usage.get("cache_creation_input_tokens") or 0
            tcr += usage.get("cache_read_input_tokens") or 0
        if msg.get("model"):
            model = msg["model"]
        if e.get("timestamp"):
            turn_ts = e["timestamp"]
        for b in msg.get("content", []):
            if not isinstance(b, dict):
                continue
            if b.get("type") == "text":
                texts.append(b.get("text", ""))
            elif b.get("type") == "tool_use":
                name = b.get("name", "?")
                inp = b.get("input", {}) or {}
                if name == "Skill":
                    skill = inp.get("skill") or inp.get("name")
                    if skill:
                        name = "Skill:" + str(skill)
                tools[name] = tools.get(name, 0) + 1
                fp = inp.get("file_path") or inp.get("path")
                if fp:
                    files[fp.rsplit("/", 1)[-1]] = True
    return {"texts": texts, "tools": tools, "files": files, "turn_ts": turn_ts,
            "input": tin, "output": tout, "cache_create": tcc, "cache_read": tcr,
            "model": model}

def _is_codex_user_prompt(e):
    if e.get("type") == "event_msg":
        p = e.get("payload") or {}
        return p.get("type") == "user_message" and bool((p.get("message") or "").strip())
    if e.get("type") == "response_item":
        p = e.get("payload") or {}
        return p.get("type") == "message" and p.get("role") == "user"
    return False

def _is_codex_event(e):
    return e.get("type") in ("session_meta", "event_msg", "response_item", "turn_context")

def _codex_prompt_text(e):
    if e.get("type") == "event_msg":
        p = e.get("payload") or {}
        if p.get("type") == "user_message":
            return (p.get("message") or "").strip()
        return ""
    if e.get("type") == "response_item":
        p = e.get("payload") or {}
        if p.get("type") != "message" or p.get("role") != "user":
            return ""
        content = p.get("content")
        if isinstance(content, str):
            return content.strip()
        if isinstance(content, list):
            return "".join(
                b.get("text", "") for b in content
                if isinstance(b, dict) and b.get("type") in ("input_text", "text", "output_text")
            ).strip()
    return ""

# A Codex skill run injects the SKILL.md as a role=user response_item opening with
# `<skill>\n<name>NAME</name>…`. This is Codex's equivalent of Claude's Skill tool_use;
# we credit it as Skill:NAME in a turn's tools. Anchored on a leading `<skill>` so prose
# that merely mentions the tag is never miscounted.
_CODEX_SKILL_RE = re.compile(r"<skill>\s*<name>([^<]+)</name>")

def codex_skill_name(e):
    """The skill NAME if event `e` is a Codex `<skill>` marker (role=user response_item),
    else '' — the invocation signal for Skill:<name> accounting."""
    if e.get("type") != "response_item":
        return ""
    text = _codex_prompt_text(e)
    if not text.lstrip().startswith("<skill>"):
        return ""
    m = _CODEX_SKILL_RE.search(text)
    return m.group(1).strip() if m else ""

def codex_session_id(path):
    """The Codex session id for a rollout file — `session_meta.payload.id`, falling back
    to the trailing UUID in the filename. This is the `<session>` in the devbrain log name
    `<worktree>.<session>.md`, so import.py can align a transcript to its captured log."""
    sid = "-".join(os.path.basename(path)[:-6].split("-")[-5:]) or "nosession"
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for line in fh:
                try:
                    e = json.loads(line)
                except Exception:
                    continue
                if e.get("type") == "session_meta":
                    return ((e.get("payload") or {}).get("id") or sid)
    except OSError:
        pass
    return sid

def _codex_cwd(e):
    if e.get("type") in ("session_meta", "turn_context"):
        return ((e.get("payload") or {}).get("cwd") or "")
    return ""

def _codex_model_from_turn_context(e):
    if e.get("type") != "turn_context":
        return ""
    p = e.get("payload") or {}
    if p.get("model"):
        return p.get("model") or ""
    settings = ((p.get("collaboration_mode") or {}).get("settings") or {})
    return settings.get("model") or ""

def _codex_details(events, prior_events=()):
    texts, tools, files = [], OrderedDict(), OrderedDict()
    tin = tout = tcc = tcr = 0
    model = ""
    turn_ts = ""

    for e in prior_events:
        model = _codex_model_from_turn_context(e) or model

    for e in events:
        model = _codex_model_from_turn_context(e) or model
        if e.get("type") == "event_msg":
            p = e.get("payload") or {}
            typ = p.get("type")
            if typ == "agent_message":
                if p.get("message"):
                    texts.append(p.get("message") or "")
                if e.get("timestamp"):
                    turn_ts = e["timestamp"]
            elif typ == "exec_command_begin":
                tools["Bash"] = tools.get("Bash", 0) + 1
            elif typ == "mcp_tool_call_begin":
                name = p.get("tool_name") or "MCP"
                tools[name] = tools.get(name, 0) + 1
            elif typ == "patch_apply_begin":
                tools["apply_patch"] = tools.get("apply_patch", 0) + 1
            elif typ == "token_count":
                info = p.get("info") or {}
                usage = info.get("last_token_usage") or {}
                if usage:
                    cached = usage.get("cached_input_tokens") or 0
                    tin += max((usage.get("input_tokens") or 0) - cached, 0)
                    tout += usage.get("output_tokens") or 0
                    tcr += cached
                else:
                    usage = info.get("total_token_usage") or {}
                    cached = usage.get("cached_input_tokens") or 0
                    tin = max(tin, max((usage.get("input_tokens") or 0) - cached, 0))
                    tout = max(tout, usage.get("output_tokens") or 0)
                    tcr = max(tcr, cached)
                model = p.get("model") or model
                if e.get("timestamp"):
                    turn_ts = e["timestamp"]
            elif typ == "task_complete":
                if p.get("last_agent_message"):
                    texts.append(p.get("last_agent_message") or "")
                if p.get("completed_at"):
                    try:
                        turn_ts = datetime.datetime.fromtimestamp(
                            p["completed_at"], datetime.timezone.utc
                        ).strftime("%Y-%m-%dT%H:%M:%SZ")
                    except Exception:
                        pass
            continue

        if e.get("type") == "response_item":
            p = e.get("payload") or {}
            if p.get("type") == "message" and p.get("role") == "assistant":
                for b in p.get("content") or []:
                    if isinstance(b, dict) and b.get("type") in ("output_text", "text"):
                        texts.append(b.get("text", ""))
                if e.get("timestamp"):
                    turn_ts = e["timestamp"]
            elif p.get("type") == "file_change":
                path = p.get("path") or p.get("file_path")
                if path:
                    files[path.rsplit("/", 1)[-1]] = True
            else:
                skill = codex_skill_name(e)   # the injected `<skill><name>…` marker → Skill:<name>
                if skill:
                    tools["Skill:" + skill] = tools.get("Skill:" + skill, 0) + 1

    return {"texts": texts, "tools": tools, "files": files, "turn_ts": turn_ts,
            "input": tin, "output": tout, "cache_create": tcc, "cache_read": tcr,
            "model": model}

def _codex_transcript_turns(events, filter_synthetic=True):
    turns, cur, prior = [], None, []
    cwd = ""
    prefer_event_msg_user = any(
        e.get("type") == "event_msg" and _codex_prompt_text(e) for e in events
    )

    def finish():
        nonlocal cur
        if not cur:
            return
        details = _codex_details(cur.pop("_events"), cur.pop("_prior"))
        cur.update(details)
        turns.append(cur)
        cur = None

    for e in events:
        cwd = _codex_cwd(e) or cwd
        prompt = _codex_prompt_text(e)
        is_boundary = bool(prompt) and (
            e.get("type") == "event_msg" or not prefer_event_msg_user
        )
        if is_boundary:
            if filter_synthetic and is_synthetic(prompt):
                prior.append(e)
                continue
            finish()
            cur = {"dt": e.get("timestamp") or "", "cwd": cwd,
                   "prompt": prompt, "_events": [], "_prior": list(prior)}
            prior.append(e)
            continue
        if cur is not None and _is_codex_event(e):
            cur["_events"].append(e)
        prior.append(e)
    finish()

    if not turns:
        details = _codex_details(events)
        if details["input"] or details["output"] or details["cache_create"] or details["cache_read"]:
            first_ts = next((e.get("timestamp") for e in events if e.get("timestamp")), "")
            turns.append({"dt": first_ts, "cwd": cwd, "prompt": "", **details})
    return turns

def _read_jsonl(path, tail_lines=None):
    with open(path, encoding="utf-8", errors="replace") as fh:
        lines = deque(fh, maxlen=tail_lines) if tail_lines else fh.readlines()
    events = []
    for ln in lines:
        ln = ln.strip()
        if not ln:
            continue
        try:
            events.append(json.loads(ln))
        except Exception:
            pass
    return events

def transcript_turns(path, tail_lines=None, filter_synthetic=True):
    """Parse transcript turns into prompt + assistant details.

    Used by live Stop capture and historical import so token/tool/Skill parsing cannot drift.
    """
    events = _read_jsonl(path, tail_lines)
    if any(_is_codex_event(e) for e in events):
        return _codex_transcript_turns(events, filter_synthetic=filter_synthetic)

    turns, cur = [], None
    for e in events:
        typ = e.get("type")
        if typ == "user" and not e.get("isSidechain"):
            prompt = _content_text(e.get("message", {}).get("content")).strip()
            if not prompt or (filter_synthetic and is_synthetic(prompt)):
                continue
            if cur:
                cur.update(_assistant_details(cur.pop("_events")))
                turns.append(cur)
            cur = {"dt": e.get("timestamp") or "", "cwd": e.get("cwd") or "",
                   "prompt": prompt, "_events": []}
        elif typ == "assistant" and cur is not None:
            cur["_events"].append(e)
    if cur:
        cur.update(_assistant_details(cur.pop("_events")))
        turns.append(cur)
    return turns

def _meta_line(turn, include_tokens=False):
    meta = []
    if turn["files"]:
        meta.append("touched: " + ", ".join(turn["files"]))
    if turn["tools"]:
        meta.append("tools: " + ", ".join(f"{k}×{v}" for k, v in turn["tools"].items()))
    if include_tokens and (turn["input"] or turn["output"] or turn["cache_create"] or turn["cache_read"]):
        tok = f"tokens: {turn['input']}/{turn['output']}/{turn['cache_create']}/{turn['cache_read']}"
        meta.append(tok + (f" · model: {turn['model']}" if turn["model"] else ""))
    return "  ·  ".join(meta)

def _iso_seconds(ts, fallback):
    try:
        return datetime.datetime.fromisoformat(ts.replace("Z", "+00:00")).strftime("%Y-%m-%dT%H:%M:%SZ")
    except Exception:
        return fallback

def response_capture(transcript, sidecar="", session="", fallback_ts="", auto=False,
                     fallback_text=""):
    events = _read_jsonl(transcript, tail_lines=1500)
    if any(_is_codex_event(e) for e in events):
        turns = _codex_transcript_turns(events, filter_synthetic=False)
        if turns:
            turn = turns[-1]
        else:
            last_user = max((i for i, e in enumerate(events) if _is_codex_user_prompt(e)),
                            default=-1)
            segment = events[last_user + 1:] if last_user >= 0 else events
            prior = events[:last_user + 1] if last_user >= 0 else ()
            turn = _codex_details(segment, prior)
            turn.update({"prompt": "", "dt": "", "cwd": ""})
    else:
        turns = transcript_turns(transcript, tail_lines=1500, filter_synthetic=False)
        if not turns:
            turn = _assistant_details(events)
            turn.update({"prompt": "", "dt": "", "cwd": ""})
        else:
            turn = turns[-1]
    if fallback_text and not turn["texts"]:
        turn["texts"].append(fallback_text)
    if sidecar and (turn["input"] or turn["output"] or turn["cache_create"] or turn["cache_read"]):
        try:
            os.makedirs(os.path.dirname(sidecar), exist_ok=True)
            rec = {"ts": _iso_seconds(turn["turn_ts"], fallback_ts), "session": session,
                   "model": turn["model"], "in": turn["input"], "out": turn["output"],
                   "cache_create": turn["cache_create"], "cache_read": turn["cache_read"],
                   "auto": bool(auto)}
            with open(sidecar, "a", encoding="utf-8") as fh:
                fh.write(json.dumps(rec) + "\n")
        except Exception:
            pass
    summary = redact(recap(turn["texts"]))
    meta = redact(_meta_line(turn, include_tokens=True))
    body = redact(sample(turn["texts"]))
    if not summary and not meta and not body:
        return ""
    return "\n".join((summary, meta, body))

_GB_WHITELIST = {"query", "search", "ask", "get", "put", "delete",
                 "list", "tag", "link", "embed", "sync", "import", "export"}
_GB_PUNCT = "();<>|&`"
_GB_SLUG = re.compile(r"[A-Za-z0-9][A-Za-z0-9._/-]*")

def gbrain_modes(cmd):
    modes = []
    for m in re.finditer(r"gbrain\s+([a-z][a-z-]*)", cmd or ""):
        sub = m.group(1)
        if sub in _GB_WHITELIST and sub not in modes:
            modes.append(sub)
    return modes

def _gb_page_arg(seq):
    for t in seq:
        if not t or t.startswith("-") or t.isdigit():
            continue
        if t.startswith("$"):
            return t
        if any(c in t for c in "<>&|;(){}"):
            return ""
        return t
    return ""

def _gb_tok(s):
    try:
        lex = shlex.shlex(s, posix=True, punctuation_chars=_GB_PUNCT)
        lex.whitespace_split = True
        lex.commenters = ""
        return list(lex)
    except ValueError:
        return None

def _gb_scan(toks):
    for i, t in enumerate(toks):
        if i + 1 < len(toks) and t.rsplit("/", 1)[-1] == "gbrain" and toks[i + 1] == "get":
            target = _gb_page_arg(toks[i + 2:])
            if target:
                return target
    return ""

def gbrain_get_target(cmd, fallback=False):
    """Best-effort page argument for a real `gbrain get` invocation."""
    if not cmd or "gbrain get " not in cmd:
        return ""
    subst = "$("
    for line in cmd.splitlines():
        target = ""
        toks = _gb_tok(line)
        if toks is not None:
            target = _gb_scan(toks)
            if not target:
                for t in toks:
                    if subst in t or "`" in t:
                        inner = _gb_tok(t.replace(subst, " ").replace("(", " ")
                                        .replace(")", " ").replace("`", " "))
                        if inner:
                            target = _gb_scan(inner)
                            if target:
                                break
        elif fallback and "gbrain get " in line:
            rest = line.split("gbrain get ", 1)[1].split()
            target = _gb_page_arg([t.strip("\"'();") for t in rest])
        if target:
            return target
    return ""

def gbrain_record(cmd, out, project, ts=""):
    modes = gbrain_modes(cmd)
    if not modes:
        return ""
    snippet = redact(re.sub(r"\s+", " ", cmd or "").strip())
    if len(snippet) > 300:
        snippet = snippet[:300] + "…"
    slugs, hits = [], 0
    for ln in (out or "").splitlines():
        if re.match(r"\[[0-9.]+\]", ln):
            hits += 1
            mm = re.match(r"\[[0-9.]+\]\s+(\S+)\s+--", ln)
            if mm and mm.group(1) not in slugs:
                slugs.append(mm.group(1))
    if "get" in modes and hits == 0:
        low = (out or "").lower()
        missed = (not (out or "").strip()) or ("page_not_found" in low) \
            or ("did you mean" in low) or ("not found" in low)
        if not missed:
            target = gbrain_get_target(cmd, fallback=True)
            if target:
                hits = 1
                if _GB_SLUG.fullmatch(target) and target not in slugs:
                    slugs.append(target)
    return json.dumps({"ts": ts, "project": project, "cmd": snippet,
                       "modes": modes, "hits": hits, "slugs": slugs},
                      ensure_ascii=False)

def remote_to_key(remote):
    """git remote URL -> <owner>__<repo> (lowercased, filesystem-safe), or None."""
    if not remote:
        return None
    url = remote[:-4] if remote.endswith(".git") else remote
    url = url.rstrip("/")
    repo = url.split("/")[-1]
    rest = url[: url.rfind("/")] if "/" in url else url
    owner = re.split(r"[:/]", rest)[-1] if rest != url else ""
    if not (owner and repo):
        return None
    return re.sub(r"[^a-z0-9._-]", "", f"{owner}__{repo}".lower().replace(" ", "-"))

# --- Event-field map: where each value lives in the harness's hook-event JSON ----------
# Background: the capture hooks are shell scripts, and the agent harness (Claude Code)
# feeds each one a JSON event on stdin — the user's prompt, the cwd, a tool call, etc.
# The hooks used to each pull fields out of that JSON inline with `jq` (a command-line
# JSON tool), so the SAME field paths were duplicated across four scripts. This dict is
# the single definition of those paths; a hook reads a field via `read-event` (below)
# instead of its own jq, so a path only ever changes in one place.
# $DEVBRAIN_HARNESS selects the map (default 'claude'); an unknown value falls back to
# 'claude' so a hook never breaks a turn.
_EVENT_FIELDS = {
    "claude": {
        "prompt":        ("prompt",),
        "cwd":           ("cwd",),
        "session":       ("session_id",),
        "transcript":    ("transcript_path",),
        "tool":          ("tool_name",),
        "command":       ("tool_input", "command"),
        "tool-response": ("tool_response",),   # value coerced to text (see _coerce_response)
        "stop-active":   ("stop_hook_active",),
    },
    "codex": {
        "prompt":        ("prompt",),
        "cwd":           ("cwd",),
        "session":       (("session_id",), ("thread_id",), ("turn_id",)),
        "transcript":    (("transcript_path",), ("agent_transcript_path",)),
        "tool":          (("tool_name",), ("tool", "name")),
        "command":       (("tool_input", "command"), ("input", "command")),
        "tool-response": (("tool_response",), ("output",)),
        "stop-active":   ("stop_hook_active",),
        "last-assistant-message": ("last_assistant_message",),
    },
}

def _coerce_response(value):
    """tool_response shape varies by harness/version — an object with .stdout/.output, or
    a bare string. Coerce to printable text, matching the old jq coercion in capture-gbrain."""
    if isinstance(value, dict):
        for k in ("stdout", "output"):
            if isinstance(value.get(k), str):
                return value[k]
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return ""
    return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)

def _read_path(obj, path):
    cur = obj
    for key in path:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(key)
        if cur is None:
            return None
    return cur

def _paths(spec):
    if not spec:
        return ()
    if isinstance(spec[0], tuple):
        return spec
    return (spec,)

def read_event(payload, field, harness=None):
    """Return one NORMALIZED field from a host-harness hook payload (JSON text), or ''
    when the field is absent (matching jq's `// empty`). `harness` defaults to
    $DEVBRAIN_HARNESS or 'claude'; an unknown harness falls back to the claude mapping."""
    harness = harness or os.environ.get("DEVBRAIN_HARNESS") or "claude"
    mapping = _EVENT_FIELDS.get(harness) or _EVENT_FIELDS["claude"]
    spec = mapping.get(field)
    if not spec:
        return ""
    try:
        obj = json.loads(payload)
    except Exception:
        return ""
    cur = None
    for path in _paths(spec):
        cur = _read_path(obj, path)
        if cur is not None:
            break
    if cur is None:
        return ""
    if field == "tool-response":
        return _coerce_response(cur)
    if isinstance(cur, bool):
        return "true" if cur else "false"
    return cur if isinstance(cur, str) else str(cur)

# --- SessionStart additionalContext --------------------------------------------------
def session_start_context(msg):
    """Wrap a nudge string in the JSON shape SessionStart hooks emit to inject context.
    Replaces the old `jq -nc` builder — json.dumps is safe for any quotes/backticks."""
    return json.dumps(
        {"hookSpecificOutput": {"hookEventName": "SessionStart", "additionalContext": msg}},
        ensure_ascii=False,
    )

# --- settings.json hook registration (the one place that edits settings.json) ----------
# These replace the `jq` merges the installer/uninstaller and nightshift used. A hook
# entry is {"hooks":[{"type":"command","command":CMD}]} (plus an optional "matcher"),
# nested under .hooks.<EVENT>. Registration is idempotent (keyed on the command string).
def _read_settings(path):
    """Parse settings.json, or {} if absent/empty. A malformed file RAISES — callers
    must abort rather than overwrite a user's real (but unparseable-here) settings."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            text = f.read().strip()
    except FileNotFoundError:
        return {}
    return json.loads(text) if text else {}

def _write_settings(path, obj):
    # Atomic write (temp file in the same dir + os.replace), so an interrupted or
    # failed write can never truncate the user's real settings.json — the parity the
    # old jq path had via `> tmp && mv`. 2-space pretty-print, matching jq's output.
    d = os.path.dirname(os.path.abspath(path)) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".settings-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(obj, f, indent=2, ensure_ascii=False)
            f.write("\n")
        os.replace(tmp, path)
    except BaseException:
        try: os.unlink(tmp)
        except OSError: pass
        raise

def _entry_commands(entry):
    return [h.get("command") for h in (entry.get("hooks") or []) if isinstance(h, dict)]

def register_hook(path, event, matcher, command):
    obj = _read_settings(path)
    hooks = obj.setdefault("hooks", {})
    arr = hooks.setdefault(event, [])
    if not any(isinstance(e, dict) and command in _entry_commands(e) for e in arr):
        entry = {}
        if matcher:
            entry["matcher"] = matcher          # matcher first, like the jq-built object
        entry["hooks"] = [{"type": "command", "command": command}]
        arr.append(entry)
    _write_settings(path, obj)

def unregister_hook(path, commands):
    cmds = set(commands)
    obj = _read_settings(path)
    hooks = obj.get("hooks")
    if not isinstance(hooks, dict):
        return
    for event, arr in hooks.items():
        if not isinstance(arr, list):
            continue
        kept = []
        for e in arr:
            if not isinstance(e, dict):
                kept.append(e); continue
            inner = e.get("hooks")
            if isinstance(inner, list):
                # Strip only the matching hook commands; KEEP an entry's sibling
                # hooks. Drop the whole entry only once it has no hooks left, so a
                # user-grouped {devbrain-cmd, their-cmd} entry never loses their cmd.
                e = {**e, "hooks": [h for h in inner
                                    if not (isinstance(h, dict) and h.get("command") in cmds)]}
            if e.get("hooks"):
                kept.append(e)
        hooks[event] = kept
    _write_settings(path, obj)

# --- CLI for the bash hooks (stdin -> stdout, no trailing-newline surprises) ----------
_STDIN_MODES = {"redact", "prompt-filter", "read-event", "session-start-context"}

def _main(argv):
    mode = argv[1] if len(argv) > 1 else ""
    # Only stdin-consuming modes read stdin — register/unregister take args, and reading
    # stdin there would block the installer (no pipe).
    data = sys.stdin.read() if mode in _STDIN_MODES else ""
    if mode == "redact":
        sys.stdout.write(redact(data))
    elif mode == "prompt-filter":
        # empty output signals "skip" (synthetic); otherwise the redacted prompt
        if not is_synthetic(data):
            sys.stdout.write(redact(data))
    elif mode == "read-event":
        # one normalized field per call (multiline-safe, like a single jq pull)
        sys.stdout.write(read_event(data, argv[2] if len(argv) > 2 else ""))
    elif mode == "session-start-context":
        sys.stdout.write(session_start_context(data))
    elif mode == "response-capture":
        try:
            sys.stdout.write(response_capture(argv[2], argv[3] if len(argv) > 3 else "",
                                              argv[4] if len(argv) > 4 else "",
                                              argv[5] if len(argv) > 5 else "",
                                              len(argv) > 6 and argv[6] == "1",
                                              argv[7] if len(argv) > 7 else ""))
        except Exception:
            return 0
    elif mode == "gbrain-record":
        try:
            sys.stdout.write(gbrain_record(argv[2], argv[3], argv[4],
                                           os.environ.get("TS", "")))
        except Exception:
            return 0
    elif mode == "register-hook":
        try:
            register_hook(argv[2], argv[3], argv[4], argv[5])
        except Exception as e:
            sys.stderr.write(f"register-hook: {e}\n")
            return 1
    elif mode == "unregister-hook":
        try:
            unregister_hook(argv[2], argv[3:])
        except Exception as e:
            sys.stderr.write(f"unregister-hook: {e}\n")
            return 1
    else:
        sys.stderr.write("usage: devbrain_lib.py {redact|prompt-filter|read-event FIELD|"
                         "session-start-context|response-capture TRANSCRIPT SIDECAR SESSION TS AUTO|"
                         "gbrain-record CMD OUT PROJECT|"
                         "register-hook FILE EVENT MATCHER CMD|"
                         "unregister-hook FILE CMD...}\n")
        return 2
    return 0

if __name__ == "__main__":
    sys.exit(_main(sys.argv))
