#!/bin/sh
# Renders Formula/devbrain.rb from a release's checksums and pushes it to the
# TheWeiHu/homebrew-devbrain tap. Replaces goreleaser's retired `brews` formula
# generator: its sanctioned successor (homebrew_casks) is macOS-only, and the
# FORMULA is what keeps `brew install devbrain` working on Linux too. Runs as
# goreleaser's global after-hook once the release assets are live; also
# runnable by hand:  scripts/brew-formula-push.sh <version> [checksums.txt]
# BREW_PUSH_DRY=1 renders the formula to stdout instead of pushing.
set -eu

version="${1:?usage: brew-formula-push.sh <version> [checksums.txt]}"
case "$version" in
  *-*) echo "brew-formula-push: prerelease/snapshot $version — skipping tap push"; exit 0 ;;
esac
sums="${2:-dist/checksums.txt}"
[ -f "$sums" ] || { echo "brew-formula-push: $sums not found" >&2; exit 1; }

sha() { grep "devbrain_${version}_${1}.tar.gz" "$sums" | awk '{print $1}' | head -1; }
for p in darwin_amd64 darwin_arm64 linux_amd64 linux_arm64; do
  [ -n "$(sha "$p")" ] || { echo "brew-formula-push: no checksum for $p in $sums" >&2; exit 1; }
done

base="https://github.com/TheWeiHu/devbrain/releases/download/v${version}"
formula() {
	cat <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by devbrain's scripts/brew-formula-push.sh. DO NOT EDIT.
class Devbrain < Formula
  desc "Turn your prompts into a durable, queryable brain any agent can resume from"
  homepage "https://github.com/TheWeiHu/devbrain"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "${base}/devbrain_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64)"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm?
      url "${base}/devbrain_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64)"

      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "${base}/devbrain_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64)"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "${base}/devbrain_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64)"
      define_method(:install) do
        bin.install "devbrain"
      end
    end
  end

  def caveats
    <<~EOS
      Wire this machine (hooks, skills, dashboard):
        devbrain install
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/devbrain version")
  end
end
EOF
}

if [ "${BREW_PUSH_DRY:-}" = "1" ]; then
	formula
	exit 0
fi

: "${GITHUB_TOKEN:?brew-formula-push: GITHUB_TOKEN required to push the tap}"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
git clone -q --depth 1 "https://x-access-token:${GITHUB_TOKEN}@github.com/TheWeiHu/homebrew-devbrain.git" "$tmp/tap"
formula >"$tmp/tap/Formula/devbrain.rb"
if git -C "$tmp/tap" diff --quiet; then
	echo "brew-formula-push: formula already current for v${version}"
	exit 0
fi
git -C "$tmp/tap" add Formula/devbrain.rb
git -C "$tmp/tap" -c user.name=devbrain-release -c user.email=release@devbrain.invalid \
	commit -qm "Brew formula update for devbrain version v${version}"
git -C "$tmp/tap" push -q origin HEAD
echo "brew-formula-push: pushed formula for v${version}"
